### ISSUE TITLE
Burrow vs Slopes

### ISSUE THREAD

**Issue by MrMadmanx2** [TwiliChaos/OriMod#4]
Bug: Spasitc Ori while burrowing through slopes
Steps to reproduce: preforming Burrow and coming into contact with any sloped block
Intended behavior: Ori should cleanly pass through
Actual behavior: Ori rapidly teleports directly above and below sloped blocks until passed
Mods installed: none
more a visual bug then a performance bug, but it does pose a danger when near lava

**Comment by Ilemni** [comment]
Fixed in 39ee2fe, forgot to close
