### ISSUE TITLE
Aimming Burrow

### ISSUE THREAD

**Issue by MrMadmanx2** [TwiliChaos/OriMod#5]
Bug: unable to aim Burrow Skill in tight spaces
Steps to reproduce: either being in a 3 block tall space, or in an area with a wall of platforms and use Burrow
Intended behavior: ori preforms Burrow in the direction of the mouse cursor
Actual behavior: ori Preforms Burrow in the direction of the block/platform closest to his head
Mods installed: None
a gripe for me as it's not consistent when I wanna burrow more downward. otherwise Burrow is fine, it's just the start of the skill

**Comment by Ilemni** [comment]
Fixed in 39ee2fe, forgot to close
