### ISSUE TITLE
Cannot summon mod bosses by using items in multiplayer while using OriMod.

### ISSUE THREAD

**Issue by Vladisvell** [TwiliChaos/OriMod#8]
Currently there are Spirit Mod and Calamity Mod that have summons not working, but ThoriumMod summons work great .
NOTE: during all tests HERO's mod, Cheat Sheet, Mod Helpers were enabled, all vanilla bosses were spawned successfully,
tested in solo multiplayer using "Host & Play".

- Test 1: 
-          Only OriMod enabled, all vanilla bosses spawned normally using their summons.
- Test 2:
-          Calamity only  - Can summon calamity bosses.
- Test 3:
-          Calamity + Spirit Mod - Bosses summoned successfully.
- Test 4:
-          Calamity + Spirit Mod + Thorium - Bosses summoned successfully.
- Test 5:
-          OriMod + calamity - Calamity summons does not work. 
- Test 6:
-          OriMod + Thorium - Can summon thorium bosses.
- Test 7:
-          OriMod + Thorium + Calamity - Only thorium bosses summoned.
- Test 8:
-          OriMod + Thorium + Calamity + Spirit Mod - only thorium bosses summoned.

- Test 9: (disabled HERO's, cheat sheet, mod helpers):
-          OriMod + Calamity + Spirit Mod  + Thorium - only thorium bosses summoned.

It seems that OriMod breaks Calamity and Spirit mod boss summon items.

Versions of 
Tmodloader (x64): 0.11.7.7
OriMod: 3.0.0.2
AnimLib: 0.1.0.4
Calamity: 1.4.5.3
Thorium: 1.6.3.11
Spirit:1.4.0.4
HEROs: 0.3.5.1
Cheat Sheet: 0.6.6.2
ModHelpers: 5.9.4

**Comment by Ilemni** [comment]
Looks like the issue was caused by a bug in our player update loop, namely, the server code trying to access stuff that we only create on the client, namely, the player trail.

After implementing the fix, I've successfully summoned a Calamity boss. I think the reason Calamity and other mod bosses failed is that those ones relied on player code not causing errors.
